### ISSUE TITLE
Dynamic properties values set

### ISSUE THREAD

**Issue by kmg-2014** [jonathancrozier/jc-samples-dynamic-properties#1]
Can you please suggest how to access the dynamic properties and set the values to these in these properties

**Comment by jonathancrozier** [comment]
Sorry for not seeing your comment, check out the [Program.cs](https://github.com/jonathancrozier/jc-samples-dynamic-properties/blob/master/JC.Samples.DynamicProperties/Program.cs) file which demonstrates how to set the dynamic property values using reflection.
